name: Publish ClickOnce

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "feature-automatic-publish" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 6.0.x
    
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Publish
        run: cd AccountManager.UI
        
        # Runs a single command using the runners shell
      - name: Publish
        run: msbuild /t:publish /p:PublishProfile=Properties\PublishProfiles\ClickOnceProfile.pubxml /p:PublishDir=../publish
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
