name: Mage test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: 
      - 'experimental'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: set test
        id: test
        run: "echo ::set-output name=testvar::test0"
        
      - name: print test
        run: "echo ${{ steps.test.outputs.testvar}}"
